//@version=5
strategy('Strategy_5', {{{header}}})

{{{date_range}}}

rsiin = input(defval=14)
fastmain = input(defval=7)
slowmain = input(defval=21)

rsi = ta.rsi(close, rsiin)
fastma = ta.ema(close, fastmain)
slowma = ta.ema(close, slowmain)

mult = input.float(defval=3)
len = input(defval=7)
[superTrend, dir] = ta.supertrend(mult, len)

plot(series=fastma, title='fast', color=color.new(color.orange, 0), linewidth=2)
plot(series=slowma, title='slow', color=color.new(color.black, 0), linewidth=2)
plot(series=superTrend, title='st', color=dir < 0 ? color.yellow : color.red, linewidth=2)
// plot(series=rsi, color=color.orange, linewidth=2)

// stopPer = input(5.0, title='Stop Loss %', type=input.float) / 100

if year > 2010
    if rsi > 50 and fastma > slowma and dir < 0
        strategy.entry('long', direction=strategy.long, when=date_range)

    if fastma < slowma
        strategy.close_all()

    // if (strategy.position_size > 0)
    //     longStop = strategy.position_avg_price * (1 - stopPer)
    //     strategy.exit('long exit', 'long', stop=longStop, trail_price=strategy.position_avg_price+5)

    if year == 2021 and month == 2 and dayofmonth == 11
        strategy.close_all()

// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © udayadds






